### PR TITLE
microverse portfolio pull request

### PR DESCRIPTION
**Pull request by clin2on3mun**
Portfolio: setup and mobile-first
1.Html containing all portfolio features 
2. dividing the page into two sections(header and headline)
3. style using the page
4. Using flexbox to display

### CODE REVIEW

**Review by bienvenuushindi — COMMENTED** [review]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @clin2on3mun ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Invalid pull request

## Invalid Code Review Request

### You do not have linter set on this project. Kindly [set up the linter](https://github.com/microverseinc/linters-config/blob/master/html-css) and please make sure that there are [no linter errors](https://github.com/microverseinc/linters-config):
- [ ] Linter should be set up correctly for this repository.
- [ ] Linter result should be green.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑
Hi @clin2on3mun ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid pull request 🙅‍♂️ 

- You do not have a linter set on this project. Kindly [set up the linter](https://github.com/microverseinc/linters-config/blob/master/html-css) and please make sure that there are [no linter errors](https://github.com/microverseinc/linters-config):
-  Linter should be set up correctly for this repository.
-  Linter result should be green.
-  when they pass, you'll see the circled part below with the number of checks 
image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

Invalid Code Review Request does not count into the code reviews limit.

**Review by bobb-Rob — CHANGES_REQUESTED** [review]
Hi @clin2on3mun , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that linters are not running at all. Kindly check that you set up your Linter files and .github folder contents.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by bobb-Rob — COMMENTED** [review]
Hi @clin2on3mun , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no linters checks running. Please fix this.
Also, your GitHub flow is also wrong because this pull request is trying to merge into a `feature` from the `main` branch. It should be the other way round, from the feature branch to the main branch. Please close this pull request, update your feature branch and push files again to that branch on GitHub, then open a new pull in the right direction.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Pull request closed without merging**
